name: Test Pull Request
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'main'
jobs:
  check_code_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i

      - name: Prettier check
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test
